[book]
title = "rust-telegram-bot"
authors = ["Jude Etuka"]
description = "Complete Telegram Bot API framework for Rust"
language = "en"
src = "src"

[output.html]
git-repository-url = "https://github.com/HexiCoreDev/rust-telegram-bot"
edit-url-template = "https://github.com/HexiCoreDev/rust-telegram-bot/edit/main/book/{path}"
default-theme = "navy"
preferred-dark-theme = "navy"
